name: yoink

version: '3.8'
services:

  # --- Grafana ---
  grafana:
    image: grafana/grafana:latest
    container_name: yoink_grafana
    ports:
      - "${GRAFANA_PORT}:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASS}
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus

  # --- Prometheus ---
  prometheus:
    image: prom/prometheus:latest
    container_name: yoink_prometheus
    ports:
      - "${PROM_PORT}:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-remote-write-receiver' # Required for k6 to push metrics
    extra_hosts:
      - "host.docker.internal:172.18.0.1"

  # --- PostgreSQL ---
  postgres:
    image: postgres:alpine
    container_name: inventory_db
    ports:
      - "${POSTGRES_PORT}:5432" #host:container
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # --- Redis ---
  redis:
    image: redis:alpine
    container_name: inventory_cache
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data

  # --- Redis Commander (GUI) ---
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: inventory_redis_gui
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "${REDIS_COMMANDER_PORT}:8081"
    depends_on:
      - redis

volumes:
  postgres_data:
  redis_data:
  prometheus_data:
  grafana_data:
